### ISSUE TITLE
Missing MAINTAINERS file

### ISSUE THREAD

**Issue by thaJeztah** [docker/leeroy#38]
I'm working on preparing the open source repositories for the new centralized maintainers file, but noticed this repository does not yet have a MAINTAINERS file.

I can create a PR to fix this, but I'm not sure who should be included as maintainer(s).

@jfrazelle are you the only maintainer, or should I add other people here?

for reference, see docker/opensource#35 and docker/docker#18321

**Comment by jfrazelle** [comment]
Calavera too 






On Sat, Dec 5, 2015 at 5:44 PM -0800, "Sebastiaan van Stijn" <notifications@github.com> wrote:












I'm working on preparing the open source repositories for the new centralized maintainers file, but noticed this repository does not yet have a MAINTAINERS file.



I can create a PR to fix this, but I'm not sure who should be included as maintainer(s).



@jfrazelle are you the only maintainer, or should I add other people here?



for reference, see docker/opensource#35 and docker/docker#18321

**Comment by jfrazelle** [comment]
And thanks!!!!






On Sat, Dec 5, 2015 at 5:44 PM -0800, "Sebastiaan van Stijn" <notifications@github.com> wrote:












I'm working on preparing the open source repositories for the new centralized maintainers file, but noticed this repository does not yet have a MAINTAINERS file.



I can create a PR to fix this, but I'm not sure who should be included as maintainer(s).



@jfrazelle are you the only maintainer, or should I add other people here?



for reference, see docker/opensource#35 and docker/docker#18321

**Comment by thaJeztah** [comment]
> Calavera too 

Cool, will do

> And thanks!!!!

Sure! Easy thing to do :+1:
